### ISSUE TITLE
1.4.4.7?

### ISSUE THREAD

**Issue by DracoMan671** [TiberiumFusion/TTPlugins#5]
will you update this to 1.4.4.7?

**Comment by TiberiumFusion** [comment]
As far as I can tell, this is not necessary.

TTPlugins is a typical .NET library and thus does not intrinsically require an exact version match against the assemblies it references. Rebuilding TTPlugins against Terraria 1.4.4.7 versus 1.4.4.5 will yield zero functional difference in the output assembly. This is in contrast to some Terraria Tweaker 2 components, which are atypical and do require an exact version match.

The release engineering for TTPlugins is as follows:
**A)** Plugin framework development: Adding new features, revising existing features and fixing bugs. These changes are often agnostic to Terraria's version. Usually, it is not necessary to update the reference the latest Terraria version for these updates; however, I do so anyways for the sake of consistency.
**B)** Compatibility keeping updates: Ensuring that the plugin framework remains 100% functional with the current version of Terraria. When these changes require changes to how TTPlugins interacts with and manipulates Terraria, often due to internal changes in Terraria's logic, it is necessary to reference the updated Terraria assembly. Signature changes, general refactoring, and overarching logic changes inside Terraria require this kind of update.

_Note: For a period of a time, I did rebuild TTPlugins against the latest Terraria version, even when no changes of type A or B were required. This was due to certain mechanics of Terraria Tweaker 2 at the time, which have since been changed. This is no longer necessary._

Terraria 1.4.4.6 and 1.4.4.7 did not make any changes that require a compatibility keeping update for TTPlugins. The current release of TTPlugins works without issue on Terraria 1.4.4.7, per my testing. If you have experienced a situation in which TTPlugins 1.2.0.1 is not functioning correctly in Terraria 1.4.4.7, please elaborate.
